const express = require("express");
const controller = require("../controllers/universidadesController");
const { requireAuth, requireAdmin } = require("../middlewares/authMiddleware");
const router = express.Router();
router.get("/", controller.listar);
router.get("/:id", controller.buscarPorId);
router.post("/", requireAuth, requireAdmin, controller.criar);
router.put("/:id", requireAuth, requireAdmin, controller.atualizar);
router.delete("/:id", requireAuth, requireAdmin, controller.excluir);
module.exports = router;
